### ISSUE TITLE
[ISSUE] after update from v0.11.0 to v0.14.0 ERROR: create_config_service failed 

### ISSUE THREAD

**Issue by ppodbielski** [timescale/timescaledb-kubernetes#402] opened 2022-07-25 12:22 UTC
> Have a look at [Troubleshooting](https://github.com/timescale/timescaledb-kubernetes/blob/master/charts/timescaledb-single/admin-guide.md#troubleshooting) or some [Common Issues](https://github.com/timescale/timescaledb-kubernetes/blob/master/charts/timescaledb-single/admin-guide.md#common-issues)

**Describe the bug**
ERROR: create_config_service failed  after update from 0.11.0 to 0.14.0

**To Reproduce**
1. Deploy timescaledb in 0.11.0
2. Update timescaledb to 0.14.0

**Expected behavior**
No error in logs, update without problems

**Logs**
timescaledb Traceback (most recent call last):
timescaledb   File "/usr/lib/python3/dist-packages/patroni/dcs/kubernetes.py", line 890, in _create_config_service
timescaledb     if not self._api.create_namespaced_service(self._namespace, body):
timescaledb   File "/usr/lib/python3/dist-packages/patroni/dcs/kubernetes.py", line 468, in wrapper
timescaledb     return getattr(self._core_v1_api, func)(*args, **kwargs)
timescaledb   File "/usr/lib/python3/dist-packages/patroni/dcs/kubernetes.py", line 404, in wrapper
timescaledb     return self._api_client.call_api(method, path, headers, body, **kwargs)
timescaledb   File "/usr/lib/python3/dist-packages/patroni/dcs/kubernetes.py", line 373, in call_api
timescaledb     return self._handle_server_response(response, _preload_content)
timescaledb   File "/usr/lib/python3/dist-packages/patroni/dcs/kubernetes.py", line 203, in _handle_server_response
timescaledb     raise k8s_client.rest.ApiException(http_resp=response)
timescaledb patroni.dcs.kubernetes.K8sClient.rest.ApiException: (403)
timescaledb Reason: Forbidden
timescaledb HTTP response headers: HTTPHeaderDict({'Audit-Id': '31cbd4eb-7321-4d6f-a006-b718d2db241d', 'Cache-Control': 'no-cache, private', 'Content-Type': 'appl ication/json', 'X-Content-Type-Options': 'nosniff', 'X-Kubernetes-Pf-Flowschema-Uid': '356ae3ba-b1a3-4b53-b05d-5c9401f67420', 'X-Kubernetes-Pf-Prioritylevel-Uid': '4bc96055-862f-4cc2-a7e9-5c17110127a7', 'Date': 'Mon, 25 Jul 2022 11:56:51 GMT', 'Content-Length': '328'})
timescaledb HTTP response body: b'{"kind":"Status","apiVersion":"v1","metadata":{},"status":"Failure","message":"services is forbidden: User \\"system:serviceaccount:timescaledb:timescaledb\\" cannot create resource \\"services\\" in API group \\"\\" in the namespace \\"timescaledb\\"","reason":"Forbidden","details":{"kind":"services"},"code":403}\n'

** this commit cause the problem**
https://github.com/timescale/timescaledb-kubernetes/commit/b6265f3b45503a454f3e4da316acc166201ff96d

**Comment by nhudson** [comment] 2022-07-27 21:26
@ppodbielski I am going to close this ticket as it's a duplicate of #405.  If you feel like that doesn't cover your issue, please re-open this issue.  Thanks!

**Closed** 2022-07-27 21:26 UTC
Labels: duplicate
