### ISSUE TITLE
unable install

### ISSUE THREAD

**Issue by acteq** [timescale/timescaledb-kubernetes#57] opened 2019-11-15 11:11 UTC
I tried to install timescaledb in a kubernetes cluster, accroding to the instruction:

random_password () { < /dev/urandom tr -dc _A-Z-a-z-0-9 | head -c32; }
helm install --name my-release charts/timescaledb-single \
    --set credentials.postgres="$(random_password)" \
    --set credentials.admin="$(random_password)" \
    --set credentials.standby="$(random_password)"

but got following error:

Error: unable to build kubernetes objects from release manifest: error validating "": error validating data: ValidationError(StatefulSet.spec.template.spec.volumes[0].emptyDir): unknown field "defaultMode" in io.k8s.api.core.v1.EmptyDirVolumeSource

then i checked the file charts/timescaledb-single/templates/statefulset-timescaledb.yaml and found that:
     volumes:
      - name: socket-directory
        emptyDir:
          defaultMode: 488 # 0750 permissions

Is it right?

**Comment by feikesteenbergen** [comment] 2019-11-25 10:02
Could not readily reproduce in the following environment:

```
$ minikube version
minikube version: v1.5.2
commit: 792dbf92a1de583fcee76f8791cff12e0c9440ad-dirty
minikube version: v1.5.2
```
```
$ kubectl version --short
Client Version: v1.16.1
Server Version: v1.16.2
```

Although indeed, the `defaultMode` is not part of `EmptyDir`. We'll remove that from the templates, however it would be great if we can reproduce this to ensure we don't run into similar issues.

**Comment by feikesteenbergen** [comment] 2019-11-25 11:18
Was able to reproduce using Helm 2.14.0:

```console
$ helm version
Client: &version.Version{SemVer:"v2.14.0", GitCommit:"05811b84a3f93603dd6c2fcfe57944dfa7ab7fd0", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.14.0", GitCommit:"05811b84a3f93603dd6c2fcfe57944dfa7ab7fd0", GitTreeState:"clean"}
```

The issue seems to be Helm related, in that it validate the schema in 2.14.0 only, it was reverted in 2.14.1:

https://github.com/helm/helm/issues/5750

**Comment by feikesteenbergen** [comment] 2019-11-25 13:29
@acteq we released https://github.com/timescale/timescaledb-kubernetes/releases/tag/v0.3.0, which should include a fix for this problem.

**Closed by feikesteenbergen** 2019-11-25 13:29 UTC
